RusLocaleFixes['menu_terry'] = 'Лицо со шрамом'
RusLocaleFixes['trophy_bains_book'] = 'Книга Бэйна'
RusLocaleFixes['trophy_bains_book_desc'] = 'Бэйн получил книгу Калиостро, как оплату за работу в госпитале в Нью-Йорке несколько лет назад.'
RusLocaleFixes['trophy_bains_book_completion_objective'] = 'Завершите контракт "Нет милосердию" на любой сложности.'
RusLocaleFixes['trophy_box_1_desc'] = 'Золото достаточно яркое, чтобы гореть, достаточно тёмное, чтобы ослеплять. Оно ждёт под землёй, мёртвое, но полное надежд, ждёт своего часа. Трое и один, четверо и один. Хранитель возвращается.'
RusLocaleFixes['trophy_box_1_completion_objective'] = 'Завершите контракты "Казино Golden Grin" и "Утёс Генри" на любой сложности.'
RusLocaleFixes['trophy_box_3_desc'] = 'От её света всякий бы бежал, но упал бы, ибо бежать невозможно. Само сердце ада поразило бы его. Из ненависти сама темнота плюнула бы в него. И не было бы ему жизни на этой Земле.'
RusLocaleFixes['trophy_box_3_completion_objective'] = 'Завершите контаркт "Утёс Генри" на любой сложности.'
RusLocaleFixes['trophy_box_2_desc'] = 'Вы стоите пред вратами тихой памяти. Один, два, три, три, один. Откройте их и узрите, как темнота поглощает мир, и возносится новый Хранитель. Zi dingir kia kanpa, zi dingir anna kanpa.'
RusLocaleFixes['trophy_box_2_completion_objective'] = 'Завершите контракт "Проникновение в ФБР" на любой сложности.'

RusLocaleFixes['trophy_black_plate_desc'] = 'Некоторые вещи лучше забыть, дабы их секреты не навредили всему миру. Предложите свою плоть, своё сердце, чтоы подкрепить темноту. Присмотритесь к бездне, и вы возрадуетесь концу, ведь трещинами и кратерами красится Земля.'
RusLocaleFixes['trophy_black_plate_completion_objective'] = 'Завершите контракт "Аукцион Shacklethorne" на любой сложности.'